nginx:
  image: 192.168.254.211:5000/nginx

  environment:
    - TZÔºù'Asia/Shanghai'

  volumes:
    - /opt/nginx:/etc/nginx
    - /opt/nginxlog:/var/log/nginx
    - /opt/nginx/hosts:/etc/hosts
    - /export/download:/opt/download

  ports:
    - "80:80/tcp"
    - "443:443/udp"
  restart: always
